# Generated by Django 2.2 on 2020-08-01 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_book_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestbook',
            name='status',
            field=models.CharField(choices=[('active', 'Активно'), ('blocked', 'Заблокировано')], default='active', max_length=20, verbose_name='Статус'),
        ),
    ]
